
styles:
  base_dir: ./test/fixtures/sass/
  output_dir: ./example/app/views/sherpa/
  layout_dir: ./lib/layouts/
  layout_template: layout.mustache
  section_template: section.mustache
  manifest:
    - base/visibility.sass
    - components/breadcrumbs.sass
    - components/wells.sass
    - mixins/box-sizing.sass
    - mixins/font-size.sass
    - ocd.sass
    - test.sass

behaviors:
  base_dir: ./test/fixtures/
  output_dir: ./example/app/views/sherpa/
  layout_dir: ./lib/layouts/
  layout_template: layout.mustache
  section_template: section.mustache
  manifest:
    - coffee/coffee.coffee
    - js/test.js

ruby:
  base_dir: ./lib/
  output_dir: ./example/app/views/sherpa/
  layout_dir: ./lib/layouts/
  layout_template: layout.mustache
  section_template: section.mustache
  manifest:
    - sherpa/utils.rb

